module.exports = {
  STRING: "STRING",
  NUMBER: "NUMBER",
  BOOLEAN: "BOOLEAN",
  IDENTIFIER: "IDENTIFIER",
  DATA_IDENTIFIER: "DATA_IDENTIFIER",
  FUNCTION_DEFINITION: "FUNCTION_DEFINITION",
  FUNCTION_CALL: "FUNCTION_CALL",
  ASSIGNMENT: "ASSIGNMENT",
  PROPERTY: "PROPERTY",
  ARRAY_PROPERTY: "ARRAY_PROPERTY",
  BINARY: "BINARY",
  UNARY: "UNARY"
};